version: '3.9'

services:
  web:
    build: 
        context: .
        
    working_dir: /app
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000 
    volumes: ##Delete later 
      - .:/app
      
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
  
    env_file:
      - .env
    restart: always

  web2:
    build: 
        context: .
        
    working_dir: /app
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:9000
    volumes: ##Delete later 
      - .:/app
       
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - static_data:/static:ro
       - media_data:/media:ro
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    
  db:
    image: postgres:17
   
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: always
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
      
    restart: always

  celery_worker:
    build: .
    command: celery -A portal worker -l DEBUG
    depends_on:
      - redis
      - db
    restart: always
    env_file:
      - .env
        
  ap_scheduler:
     build: .
     command : python manage.py start_scheduler
     depends_on:
         - db
     restart: always
     env_file:
        - .env
  
 

volumes:
    pgdata:

    static_data:
    media_data: