version: '3.9'

services:
  web:
    build: 
        context: .
        
    working_dir: /app
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000 
    volumes: ##Delete later 
      - .:/app
      
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=portal.settings
      - DATABASE_URL=postgres://postgres:1246@db:5432/django-prod
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - PYTHONPATH=/app
      - DJANGO_CONFIGURATION=Prod
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_SCHEDULE_DAY=2
      - DJANGO_TWILIO_ACCCOUNT_SID=${TWILIO_ACCCOUNT_SID}
      - DJANGO_TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - DJANGO_TWILIO_MSG_SID=${TWILIO_MSG_SID}
    restart: always

  web2:
    build: 
        context: .
        
    working_dir: /app
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:9000
    volumes: ##Delete later 
      - .:/app
       
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=portal.settings
      - DATABASE_URL=postgres://postgres:1246@db:5432/django-prod
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - PYTHONPATH=/app
      - DJANGO_CONFIGURATION=Prod
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_SCHEDULE_DAY=2
      - DJANGO_TWILIO_ACCCOUNT_SID=${TWILIO_ACCCOUNT_SID}
      - DJANGO_TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - DJANGO_TWILIO_MSG_SID=${TWILIO_MSG_SID}
    restart: always
    
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - static_data:/static:ro
       - media_data:/media:ro
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: django-prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1246
      
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
      
    restart: always

  celery_worker:
    build: .
    command: celery -A portal worker -l DEBUG
    depends_on:
      - redis
      - db
    restart: always
    environment:
        - DJANGO_SETTINGS_MODULE=portal.settings
        - DATABASE_URL=postgres://postgres:1246@db:5432/django-prod
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - PYTHONPATH=/app
        - DJANGO_CONFIGURATION=Prod
        - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
        - DJANGO_SCHEDULE_DAY=2
        - DJANGO_TWILIO_ACCCOUNT_SID=${TWILIO_ACCCOUNT_SID}
        - DJANGO_TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
        - DJANGO_TWILIO_MSG_SID=${TWILIO_MSG_SID}
  ap_scheduler:
     build: .
     command : python manage.py start_scheduler
     depends_on:
      - db
     restart: always
     environment:
        - DJANGO_SETTINGS_MODULE=portal.settings
        - DATABASE_URL=postgres://postgres:1246@db:5432/django-prod
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - PYTHONPATH=/app
        - DJANGO_CONFIGURATION=Prod
        - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
        - DJANGO_SCHEDULE_DAY=2
        - DJANGO_TWILIO_ACCCOUNT_SID=${TWILIO_ACCCOUNT_SID}
        - DJANGO_TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
        - DJANGO_TWILIO_MSG_SID=${TWILIO_MSG_SID}
  
 

volumes:
    pgdata:

    static_data:
    media_data: