# Generated by Django 5.2.4 on 2025-07-31 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='column',
        ),
        migrations.AddField(
            model_name='chartdata',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
