# Generated by Django 5.2.4 on 2025-07-19 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='message_targets', to=settings.AUTH_USER_MODEL),
        ),
    ]
