# Generated by Django 5.2.4 on 2025-09-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.TextField(blank=True, default='No status yet', max_length=80, null=True),
        ),
    ]
