# Generated by Django 5.2.4 on 2025-08-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_chartdata_column_chartdata_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='tasks',
        ),
    ]
