# Generated by Django 5.2.4 on 2025-09-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
    ]
