# Generated by Django 5.2.4 on 2025-08-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_schedule_unscheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='unscheduled',
            field=models.BooleanField(default=False),
        ),
    ]
