# Generated by Django 5.2.4 on 2025-07-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userprofile_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
    ]
