# Generated by Django 5.2.4 on 2025-09-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_milestone_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
