# Generated by Django 5.2.4 on 2025-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_chart_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
