# Generated by Django 5.2.4 on 2025-08-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_schedule_unscheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='vacation',
            field=models.BooleanField(default=False),
        ),
    ]
