# Generated by Django 5.2.4 on 2025-07-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_reports_recipient_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
    ]
