# Generated by Django 5.2.4 on 2025-08-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_schedule_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='logged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LogginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
    ]
