# Generated by Django 5.2.4 on 2025-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_task_alter_messages_title_messages_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tasks',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='many_tasks', to='dashboard.task'),
        ),
    ]
