# Generated by Django 5.2.4 on 2025-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_chart_teams_alter_task_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='start_date',
            field=models.DateField(),
        ),
    ]
