# Generated by Django 5.2.4 on 2025-08-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_stats_logged_logginrecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessages',
            index=models.Index(fields=['created_at'], name='dashboard_c_created_e82d81_idx'),
        ),
        migrations.AddIndex(
            model_name='messagescopy',
            index=models.Index(fields=['user'], name='dashboard_m_user_id_54a2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='messagescopy',
            index=models.Index(fields=['timestamp'], name='dashboard_m_timesta_d22ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagescopy',
            index=models.Index(fields=['id'], name='dashboard_m_id_7ad2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user'], name='dashboard_s_user_id_bbf1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['week_range'], name='dashboard_s_week_ra_7b1387_idx'),
        ),
    ]
