# Generated by Django 5.2.4 on 2025-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='unscheduled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vacation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
