# Generated by Django 5.2.4 on 2025-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_chart_end_date_alter_chart_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='teams',
            field=models.ManyToManyField(to='dashboard.team'),
        ),
    ]
