# Generated by Django 5.2.4 on 2025-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_userprofile_tasks_userprofile_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='task_users', to='dashboard.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='user_tasks', to='dashboard.task'),
        ),
    ]
