# Generated by Django 5.2.4 on 2025-08-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_chart_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aproved_by', to='dashboard.userprofile'),
        ),
        migrations.DeleteModel(
            name='CompletedTasks',
        ),
    ]
