# Generated by Django 5.2.4 on 2025-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_schedule_unscheduled_alter_schedule_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='unscheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vacation',
            field=models.BooleanField(default=False),
        ),
    ]
