# Generated by Django 5.2.4 on 2025-07-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tasks',
        ),
    ]
