# Generated by Django 5.2.4 on 2025-08-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_task_approved_by_delete_completedtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsection',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.chart'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='sections',
            field=models.ManyToManyField(null=True, related_name='sections_in_charts', to='dashboard.chartsection'),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aproved_by', to='dashboard.userprofile'),
        ),
    ]
