# Generated by Django 5.2.4 on 2025-09-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_schedule_unscheduled_alter_schedule_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
