# Generated by Django 5.2.4 on 2025-07-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_userprofile_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
