# Generated by Django 5.2.4 on 2025-08-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_chartsection_chart_alter_chart_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='sections',
        ),
    ]
