# Generated by Django 5.2.4 on 2025-08-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_milestone_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='month',
            new_name='date',
        ),
    ]
