# Generated by Django 5.2.4 on 2025-09-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_options_delete_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='late',
            field=models.BooleanField(default=True),
        ),
    ]
