# Generated by Django 5.2.4 on 2025-07-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_task_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2025-07-22 15:00'),
        ),
    ]
