# Generated by Django 5.2.4 on 2025-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
