# Generated by Django 5.2.4 on 2025-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_options_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='help',
            field=models.BooleanField(default=True),
        ),
    ]
