# Generated by Django 5.2.4 on 2025-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.CharField(blank=True, default='9-17', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
