# Generated by Django 5.2.4 on 2025-08-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_schedule_friday_schedule_monday_schedule_saturday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_day', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.CharField(blank=True, help_text='9-17', null=True),
        ),
    ]
