# Generated by Django 5.2.4 on 2025-09-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_options_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='active_task',
            field=models.BooleanField(default=True),
        ),
    ]
