# Generated by Django 5.2.4 on 2025-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_goal_type_goal_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.ManyToManyField(to='dashboard.goaltype'),
        ),
    ]
