# Generated by Django 5.2.4 on 2025-07-23 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team A', max_length=40, null=True)),
                ('lead', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
                ('members', models.ManyToManyField(related_name='team_members', to='dashboard.userprofile')),
            ],
        ),
    ]
