# Generated by Django 5.2.4 on 2025-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_goaltype_remove_goal_type_goal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='value_type',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
