# Generated by Django 5.2.4 on 2025-09-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_options_active_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
