# Generated by Django 5.2.4 on 2025-07-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
