# Generated by Django 5.2.4 on 2025-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_schedulestart_alter_schedule_monday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleStart',
        ),
    ]
