# Generated by Django 5.2.4 on 2025-08-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_weekrange_delete_schedulestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.weekrange'),
        ),
    ]
