# Generated by Django 5.2.4 on 2025-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_goal_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='stats',
            name='late',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
