# Generated by Django 5.2.4 on 2025-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_goal_time_limit_stats_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
