# Generated by Django 5.2.4 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_team_lead_alter_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='user_profile_team', to='dashboard.team'),
        ),
    ]
