# Generated by Django 5.2.4 on 2025-08-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_schedule_week_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.weekrange'),
        ),
    ]
