# Generated by Django 5.2.4 on 2025-08-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_schedule_week_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
    ]
