# Generated by Django 5.2.4 on 2025-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_name_team_team_name_remove_team_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_userprofiles', to='dashboard.userprofile'),
        ),
    ]
