# Generated by Django 5.2.4 on 2025-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_goal_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
