# Generated by Django 5.2.4 on 2025-08-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_goal_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='value_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.valuetype'),
            preserve_default=False,
        ),
    ]
