# Generated by Django 5.2.4 on 2025-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_goal_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltype',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
