# Generated by Django 5.2.4 on 2025-08-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_schedule_end_date_remove_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='unscheduled',
            field=models.BooleanField(default=False),
        ),
    ]
