# Generated by Django 5.2.4 on 2025-08-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_goal_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.goaltype'),
            preserve_default=False,
        ),
    ]
