# Generated by Django 5.2.4 on 2025-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_userprofile_availability_userprofile_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
