# Generated by Django 5.2.4 on 2025-09-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_goal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='value_type',
        ),
        migrations.AddField(
            model_name='goaltype',
            name='value_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.valuetype'),
        ),
    ]
