# Generated by Django 5.2.4 on 2025-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_goal_name_remove_goal_type_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
