# Generated by Django 5.2.4 on 2025-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_schedule_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='request_pending',
            field=models.BooleanField(default=False),
        ),
    ]
