# Generated by Django 5.2.4 on 2025-09-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_goal_value_type_goaltype_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.goaltype'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
