# Generated by Django 5.2.4 on 2025-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_milestone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
