# Generated by Django 5.2.4 on 2025-08-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0020_userprofile_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stars',
        ),
        migrations.AddField(
            model_name='stats',
            name='star_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='stars',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['object_id'], name='dashboard_s_object__c1fcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['timestamp'], name='dashboard_s_timesta_6d96de_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['stars'], name='dashboard_s_stars_2d9990_idx'),
        ),
    ]
