# Generated by Django 5.2.4 on 2025-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_schedule_request_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
