# Generated by Django 5.2.4 on 2025-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_picture_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
