# Generated by Django 5.2.4 on 2025-09-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_goal_type_alter_goal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='report_not_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='unscheduled',
            field=models.BooleanField(default=True),
        ),
    ]
