# Generated by Django 5.2.4 on 2025-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_messages_content_type_messages_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
