# Generated by Django 5.2.4 on 2025-08-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_messages_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='days_missed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='days_scheduled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='late_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unfinished_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denied_tasks', models.PositiveIntegerField(default=0)),
                ('late_tasks', models.PositiveIntegerField(default=0)),
                ('urgent_tasks_success', models.PositiveIntegerField(default=0)),
                ('approved_tasks', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.team')),
            ],
        ),
    ]
