# Generated by Django 5.2.4 on 2025-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_stats_report_not_done_stats_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='unfinished_tasks',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days_scheduled',
            field=models.IntegerField(default=0),
        ),
    ]
