# Generated by Django 5.2.4 on 2025-09-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_stats_unfinished_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='days_scheduled',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='unscheduled',
            field=models.BooleanField(default=False),
        ),
    ]
