# Generated by Django 5.2.4 on 2025-08-08 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0022_userprofile_completed_tasks_userprofile_days_missed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='approved_tasks',
            new_name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='days_missed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='days_scheduled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='late_tasks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unfinished_tasks',
        ),
        migrations.AddField(
            model_name='stats',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stats',
            name='days_missed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='days_scheduled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='unfinished_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
