# Generated by Django 5.2.4 on 2025-07-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_messages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pinned_msg',
            field=models.TextField(null=True),
        ),
    ]
