# Generated by Django 5.2.4 on 2025-08-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_approved_tasks_stats_completed_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
