# Generated by Django 5.2.4 on 2025-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_schedule_days_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='textfriday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='textmonday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='textsaturday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='textsunday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='textthursday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='texttuesday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='textwednesday',
            field=models.CharField(blank=True, null=True),
        ),
    ]
