# Generated by Django 5.2.4 on 2025-07-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_team_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pinned_msg',
            field=models.TextField(default='---', null=True),
        ),
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=True)),
                ('urgent', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('creation_date', models.DateField()),
                ('picture', models.BinaryField(blank=True, editable=True, null=True)),
                ('completion_note', models.TextField(null=True)),
                ('submitted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
                ('users', models.ManyToManyField(related_name='task_completed_users', to='dashboard.userprofile')),
            ],
        ),
    ]
