# Generated by Django 5.2.4 on 2025-09-17 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_schedule_textfriday_schedule_textmonday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='picture',
        ),
        migrations.AddField(
            model_name='task',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_approval',
            field=models.ManyToManyField(related_name='approval_task', to='dashboard.taskapproval'),
        ),
    ]
