# Generated by Django 5.2.4 on 2025-09-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_report_time_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
    ]
