# Generated by Django 5.2.4 on 2025-08-10 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_task_chart_alter_task_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
