# Generated by Django 5.2.4 on 2025-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_team_pinned_msg_completedtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
