# Generated by Django 5.2.4 on 2025-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_task_picture_task_pending_taskapproval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskapproval',
            name='number',
        ),
        migrations.AddField(
            model_name='task',
            name='approvals',
            field=models.IntegerField(default=0),
        ),
    ]
