# Generated by Django 5.2.4 on 2025-07-27 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_completedtasks_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
    ]
