# Generated by Django 5.2.4 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_taskapproval_number_task_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_approval',
        ),
        migrations.AddField(
            model_name='task',
            name='task_approvals',
            field=models.ManyToManyField(related_name='approval_task', to='dashboard.userprofile'),
        ),
        migrations.DeleteModel(
            name='TaskApproval',
        ),
    ]
