# Generated by Django 5.2.4 on 2025-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.TextField(blank=True, default='No status', max_length=90, null=True),
        ),
    ]
