# Generated by Django 5.2.4 on 2025-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_task_task_approval_task_task_approvals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='task_approval_modal',
            field=models.BooleanField(default=False),
        ),
    ]
