# Generated by Django 5.2.4 on 2025-07-27 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_completedtasks_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='aproved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aproved_by', to='dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
        migrations.AlterField(
            model_name='completedtasks',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
    ]
