# Generated by Django 5.2.4 on 2025-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_task_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='submission',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
