# Generated by Django 5.2.4 on 2025-07-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_completedtasks_aproved_by_task_completion_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
