# Generated by Django 5.2.4 on 2025-09-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_agenda_event_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='end',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='start',
        ),
        migrations.AddField(
            model_name='agenda',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agenda')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.event')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='days',
            field=models.ManyToManyField(related_name='agenda_day', to='dashboard.day'),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
