# Generated by Django 5.2.4 on 2025-08-13 22:07

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_task_name_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=dashboard.models.object_directory_path),
        ),
    ]
