# Generated by Django 5.2.4 on 2025-07-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_task_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtasks',
            old_name='aproved_by',
            new_name='approved_by',
        ),
    ]
