# Generated by Django 5.2.4 on 2025-07-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_rename_aproved_by_completedtasks_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='deny_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
