# Generated by Django 5.2.4 on 2025-09-19 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_rename_user_event_users_remove_agenda_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
        migrations.RemoveField(
            model_name='day',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_users', to='dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='day',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.event'),
        ),
    ]
