# Generated by Django 5.2.4 on 2025-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_day_team_day_user_remove_day_event_alter_event_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='content',
            field=models.CharField(blank=True, null=True),
        ),
    ]
