# Generated by Django 5.2.4 on 2025-09-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_day_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_days', to='dashboard.userprofile'),
        ),
    ]
