# Generated by Django 5.2.4 on 2025-07-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_chatmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
    ]
