# Generated by Django 5.2.4 on 2025-08-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_document_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
