# Generated by Django 5.2.4 on 2025-08-13 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
