# Generated by Django 5.2.4 on 2025-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_day_event_event_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_days', to='dashboard.day'),
        ),
    ]
