# Generated by Django 5.2.4 on 2025-07-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_chatmessages_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
