# Generated by Django 5.2.4 on 2025-07-29 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_chatmessages_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='dashboard.userprofile'),
        ),
    ]
