# Generated by Django 5.2.4 on 2025-08-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_document_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
