# Generated by Django 5.2.4 on 2025-09-19 21:06

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_event_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=dashboard.models.object_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.eventicon'),
        ),
    ]
