# Generated by Django 5.2.4 on 2025-07-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_messagescopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='fowarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagescopy',
            name='fowarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagescopy',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
