# Generated by Django 5.2.4 on 2025-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_eventicon_event_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventicon',
            name='image',
            field=models.ImageField(upload_to='event_icons/'),
        ),
    ]
