# Generated by Django 5.2.4 on 2025-08-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_document_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='duration',
        ),
        migrations.AddField(
            model_name='subtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
    ]
