# Generated by Django 5.2.4 on 2025-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_subtask_duration_subtask_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
