# Generated by Django 5.2.4 on 2025-08-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_subtask_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='messagescopy',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='messagescopy',
            name='picture',
        ),
    ]
