# Generated by Django 5.2.4 on 2025-07-29 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_remove_messages_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='fowarded',
            field=models.BooleanField(),
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='messagescopy',
            name='fowarded',
            field=models.BooleanField(),
        ),
        migrations.RemoveField(
            model_name='messagescopy',
            name='recipient',
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='messagescopy',
            name='recipient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_copy', to='dashboard.userprofile'),
        ),
    ]
