# Generated by Django 5.2.4 on 2025-08-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_remove_messages_content_type_remove_messages_picture_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['id'], name='dashboard_c_id_65e202_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['start_date'], name='dashboard_c_start_d_63ebb2_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['end_date'], name='dashboard_c_end_dat_87ebe3_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['user'], name='dashboard_m_user_id_5afbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['timestamp'], name='dashboard_m_timesta_94d61d_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['id'], name='dashboard_m_id_b94aff_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed'], name='dashboard_t_complet_5bea0a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='dashboard_t_due_dat_b69917_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['id'], name='dashboard_t_id_7d6048_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creation_date'], name='dashboard_t_creatio_f06901_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_lead'], name='dashboard_t_team_le_61750d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['id'], name='dashboard_t_id_1d4008_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='dashboard_t_name_246b05_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['team'], name='dashboard_u_team_id_a68f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['id'], name='dashboard_u_id_695ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='dashboard_u_user_id_48b5f5_idx'),
        ),
    ]
