# Generated by Django 5.2.4 on 2025-07-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_messages_fowarded_remove_messages_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='messagescopy',
            name='recipient',
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='receiver', to='dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='messagescopy',
            name='recipient',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='receiver_copy', to='dashboard.userprofile'),
        ),
    ]
