# Generated by Django 5.2.4 on 2025-08-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_chart_dashboard_c_id_65e202_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
