# Generated by Django 5.2.4 on 2025-08-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_validationkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidationKey',
        ),
    ]
