# Generated by Django 5.2.4 on 2025-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_remove_messages_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='fowarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagescopy',
            name='fowarded',
            field=models.BooleanField(default=False),
        ),
    ]
