# Generated by Django 5.2.4 on 2025-07-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_messages_fowarded_alter_messagescopy_fowarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='fowarded',
            new_name='forwarded',
        ),
        migrations.RenameField(
            model_name='messagescopy',
            old_name='fowarded',
            new_name='forwarded',
        ),
    ]
