# Generated by Django 5.2.4 on 2025-08-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField()),
                ('how', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
