# Generated by Django 5.2.4 on 2025-07-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_rename_fowarded_messages_forwarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='forwarded_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='messagescopy',
            name='forwarded_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
    ]
