# Generated by Django 5.2.4 on 2025-07-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_messages_forwarded_from_messagescopy_forwarded_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='forwarded_from',
            new_name='forwarded_by',
        ),
        migrations.RenameField(
            model_name='messagescopy',
            old_name='forwarded_from',
            new_name='forwarded_by',
        ),
    ]
