# Generated by Django 5.2.4 on 2025-08-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_resource_alter_chart_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='how',
            field=models.TextField(),
        ),
    ]
