# Generated by Django 5.2.4 on 2025-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_resourcecategory_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='management',
            field=models.BooleanField(null=True),
        ),
    ]
